name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64, arm64]

    env:
      PROJECT_FILE_PATH: google-chat-desktop/google-chat-desktop.csproj
      DOTNET_VERSION: '10.0.x'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_FILE_PATH }} -r win-${{ matrix.architecture }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_FILE_PATH }} --configuration Release --no-restore -r win-${{ matrix.architecture }}

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_FILE_PATH }} --configuration Release --runtime win-${{ matrix.architecture }} --output ./publish_temp/google-chat-desktop --self-contained true

      - name: Create zip archive
        run: |
          Compress-Archive -Path ./publish_temp/google-chat-desktop -DestinationPath ./google-chat-desktop-${{ matrix.architecture }}-${{ github.ref_name }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-asset-${{ matrix.architecture }}
          path: ./google-chat-desktop-${{ matrix.architecture }}-${{ github.ref_name }}.zip

  create_release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine if prerelease
        id: check
        run: |
          # origin/main ブランチに現在のコミットが含まれているか確認
          if git branch -r --contains ${{ github.sha }} | grep -q "origin/main"; then
            echo "prerelease=false" >> $GITHUB_OUTPUT
          else
            echo "prerelease=true" >> $GITHUB_OUTPUT
          fi

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: release-asset-*
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: google-chat-desktop-*-${{ github.ref_name }}.zip
          draft: false
          prerelease: ${{ steps.check.outputs.prerelease == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
